"""add_celular_fields

Revision ID: 0efadbc94b52
Revises: 74f8449d548a
Create Date: 2026-07-24 05:07:25.685764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0efadbc94b52'
down_revision = '74f8449d548a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imei2', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bateria', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('memoria', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('proveedor', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('proveedor')
        batch_op.drop_column('memoria')
        batch_op.drop_column('bateria')
        batch_op.drop_column('color')
        batch_op.drop_column('imei2')

    # ### end Alembic commands ###
