"""Retomas

Revision ID: 74f8449d548a
Revises: 03acf7581d1b
Create Date: 2026-07-24 04:06:08.482399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f8449d548a'
down_revision = '03acf7581d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arqueo_caja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_retomas_sistema', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arqueo_caja', schema=None) as batch_op:
        batch_op.drop_column('total_retomas_sistema')

    # ### end Alembic commands ###
